import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Plate } from '@udecode/plate';
import dynamic from 'next/dynamic';
const Reactour = dynamic(() => import('reactour'), { ssr: false });

export default function Home() {
  return (
    <div className={styles.container}>
      <Plate />
      <Reactour isOpen={false} steps={[]} onRequestClose={() => {}} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{`Check the console for errors :)`}</h1>
      </main>
    </div>
  );
}
